# -*- encoding: utf-8 -*-
{
    'name': 'Theme Alan',
    'category': 'Theme/eCommerce',
    'sequence': 1000,
    'version': '1.3.0.3',
    'license': 'OPL-1',
    'author': 'Atharva System',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'live_test_url': 'https://alan-v16-furniture.atharvasystem.com/',
    'description': """Theme Alan is one of the most powerful, amazing and flexible theme on Odoo store.""",
    'summary': 'Theme Alan is one of the most powerful, amazing and flexible theme on Odoo store.',
    'depends': ['atharva_theme_base'],
    'data': [
        'data/data.xml',
        'data/ir_sequence.xml',
        'views/snippets/s_img_hotspot_tr.xml',
        'views/snippets/s_megamenu.xml',
        'views/mixins/template.xml',
        'views/shop.xml',
        'views/header/headers.xml',
        'views/header/switch.xml',
        'views/footer/footers.xml',
        'views/footer/switch.xml',
        'views/login.xml',
        'views/mini_cart.xml',
        'views/quick_view.xml',
        'views/similar_product.xml',
        'views/product_details.xml',
        'views/brand.xml',
        'views/snippets/s_dynamic_snippet.xml',
        'views/snippets/s_brand_product.xml',
        'views/snippets/s_product_slider.xml',
        'views/snippets/s_category_product.xml',
        'views/snippets/s_product_banner.xml',
        'views/snippets/s_category_slider.xml',
        'views/snippets/s_brand_slider.xml',
        'views/snippets/s_blog_slider.xml',
        'views/snippets/s_website_builder.xml',
        'views/snippets/s_img_hotspot.xml',
        # 'views/mixins/mixins.xml'
    ],
    'assets': {
        'web._assets_primary_variables': [
            '/theme_alan/static/src/scss/assets_primary_variables/*.scss'
        ],
        'web._assets_frontend_helpers': [
            '/theme_alan/static/src/scss/assets_frontend_helpers/*.scss'
        ],
        'web.assets_frontend': [
            '/theme_alan/static/src/js/frontends/*.js',
            '/theme_alan/static/src/scss/frontend/*',
            '/theme_alan/static/src/xml/mixins/*',
        ],
        'web.assets_backend': [
            ('include', 'website.assets_editor'),
            '/theme_alan/static/src/scss/frame_dialog.scss',
            '/theme_alan/static/src/scss/frontend/iconfont.scss',
        ],
        'website.assets_editor':[
            '/theme_alan/static/src/js/editors/components/AlanTouch/*',
            '/theme_alan/static/src/js/editors/components/Menus/*'
        ],
        'website.assets_wysiwyg':[
            '/theme_alan/static/src/xml/frame_static_snippets/**/*',
            '/theme_alan/static/src/xml/website_builder/*.xml',
            '/theme_alan/static/src/xml/website_builder/**/*.xml',
            '/theme_alan/static/src/xml/mixins/*',
            '/theme_alan/static/src/js/base/mixins.js',
            '/theme_alan/static/src/scss/frontend/*',
            '/theme_alan/static/src/scss/frame_dialog.scss',
            '/theme_alan/static/src/js/registries.js',
            '/theme_alan/static/src/js/editors/components/UserInfo/*',
            '/theme_alan/static/src/js/editors/snippets/DynamicSnippets/**/*',
            '/theme_alan/static/src/js/editors/snippets/StaticSnippets/*',
            '/theme_alan/static/src/js/editors/components/SelectData/*',
            '/theme_alan/static/src/js/editors/snippets/Megamenu/**/*',
            '/theme_alan/static/src/js/editors/snippets/ImageHotspot/*',
            '/theme_alan/static/src/js/editors/components/SnippetPicker/*',
            '/theme_alan/static/src/js/editors/components/SnippetBox/*',
            '/theme_alan/static/src/js/editors/components/FramePreview/*',
            '/theme_alan/static/src/js/editors/components/FrameData/*',
            '/theme_alan/static/src/js/editors/components/FrameMaker/*',
            '/theme_alan/static/src/js/editors/components/SnippetBuilder/*',
            '/theme_alan/static/src/js/editors/snippets/WebsiteBuilder/*',
            '/theme_alan/static/src/js/snippet_config.js',
        ],
    },
    'price': 224.00,
    'currency': 'EUR',
    'images': ['static/description/alan_description.jpg','static/description/alan_screenshot.gif'],
    'application': False,
    'auto_install': False,
}
