{
    'name': 'carwash',
    'version': '1.5.19',
    'author': 'Autoronics',
    'summary': 'carwash Home Management System',
    'sequence': 1,
    'description': 'This is carwash home management system software suppored in Odoo',
    'category': 'carwash',
    'website': 'https://www.autoronics.com',
    'depends': ['base', 'website', 'product'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        #'views/all_records_list.xml',
        # 'views/record_item.xml',
        #'views/form_response.xml',
        #'views/sale_order.xml',
        #'views/form_request.xml',
        #'views/car_view.xml',
        #'views/extra.xml',
        #'views/city.xml',
        #'views/snippets/s_booking_widget.xml',
        #'views/snippets/demo/s_cart_product/s_cart_products.xml',
        #'views/snippets/demo/snippets.xml',
        'wizard/wizard_show_details_view.xml',
        'views/carwash_view.xml',
        #'views/inherit_view.xml',
        # 'views/snippets/s_car_select.xml',
        # 'views/snippets/s_reservation_form.xml',
        # 'reports/links_report_views.xml',
        #'data/antalyahermes.xml'
    ],
    'assets': {
        'web.assets_frontend': [
            # 'carwash/static/src/css/intlTelInput.css',
            # 'carwash/static/src/css/jquery-clockpicker.min.css',
            # 'carwash/static/src/css/style.css',
            # 'carwash/static/src/js/jquery-clockpicker.min.js',
            # 'carwash/static/src/js/intlTelInput.min.js',
            # 'carwash/static/src/js/utils.js',
            # 'carwash/static/src/js/reservation.js',
            # 'carwash/static/src/js/script.js',
            'carwash/static/src/css/xml_form.css',
            'carwash/static/src/js/thunkableWebviewerExtension.js',
        ],
        'web.assets_backend': [
            'carwash/static/src/js/thunkableWebviewerExtension.js',
            'carwash/static/src/css/xml_form.css',
            'carwash/static/src/css/theme.css',
            #'carwash/static/src/js/test.js',
        ],
    },
}
